



{
  "project_root": "/absolute/path/to/your/project",
  "work_root": "/absolute/path/to/agentic-evolve-run",
  "prepare_command": "rsync -a --delete \"$EVOLVE_CANDIDATE_DIR/\" /absolute/path/to/predefined/build/tree/",
  "compile_command": "",
  "deploy_command": "",
  "device_evaluate_command": "",
  "evaluate_command": "cd /absolute/path/to/eval && ./run_eval.sh",
  "optimization_goal": "Maximize evaluator score by improving sustained FPS, frame-time stability, and useful work per watt without changing externally visible behavior.",
  "target_fps": 120.0,
  "target_fps_metric": "fps_1pct_low",
  "metric_notes": "Treat score wins as coming from lower per-frame CPU/GPU work, fewer synchronization stalls, less memory bandwidth and allocation churn, fewer wakeups or polling loops, less logging, and fewer redundant device/API calls.",
  "primary_metric_keys": ["fps_1pct_low", "power_w"],
  "metric_objectives": {
    "score": "maximize",
    "fps": "maximize",
    "fps_avg": "maximize",
    "fps_min": "maximize",
    "fps_1pct_low": "maximize",
    "fps_0_1pct_low": "maximize",
    "frame_time_ms": "minimize",
    "frame_time_avg_ms": "minimize",
    "frame_time_p95_ms": "minimize",
    "frame_time_p99_ms": "minimize",
    "power_w": "minimize",
    "power_avg_w": "minimize",
    "cpu_power_w": "minimize",
    "gpu_power_w": "minimize",
    "package_power_w": "minimize",
    "energy_j": "minimize"
  },
  "mutable_extensions": [".cpp", ".cc", ".cxx"],
  "mutable_header_extensions": [".h", ".hh", ".hpp", ".hxx"],
  "allow_header_mutations": true,
  "pair_headers_with_sources": true,
  "max_paired_headers_per_source": 2,
  "immutable_extensions": [],
  "ignore_dirs": [".git", "build", "dist", "out", "cmake-build-debug", "cmake-build-release"],
  "generations": 100,
  "children_per_generation": 10,
  "max_focus_files_per_child": 3,
  "enable_constant_tuning_plans": true,
  "constant_tuning_plan_fraction": 0.3,
  "max_constant_tuning_plans_per_generation": 4,
  "max_constant_hints_per_file": 16,
  "enable_algorithmic_model_plans": true,
  "algorithmic_model_plan_fraction": 0.4,
  "max_algorithmic_model_plans_per_generation": 5,
  "max_model_hints_per_file": 16,
  "max_llm_workers": 8,
  "max_eval_workers": 1,
  "parent_pool_size": 8,
  "elite_keep": 16,
  "archive_keep_per_signature": 2,
  "compile_fail_score": -1000000000.0,
  "max_compile_repairs": 2,
  "planner_children_per_call": 10,
  "enable_llm_summaries": true,
  "include_full_target_files": true,
  "max_context_chars_per_file": 0,
  "max_neighbor_chars_total": 0,
  "max_neighbor_chars_per_file": 0,
  "max_repair_error_chars": 0,
  "max_project_summary_files": 80,
  "enable_deep_project_analysis": true,
  "max_project_analysis_files": 0,
  "max_project_analysis_chars_per_file": 0,
  "max_file_summary_output_tokens": 8000,
  "max_project_analysis_output_tokens": 240000,
  "max_planning_output_tokens": 120000,
  "enable_hypothesis_learning": true,
  "max_hypothesis_learning_output_tokens": 120000,
  "max_hypothesis_learning_log_chars": 40000,
  "strategy_memory_keep": 20,
  "review_pass": true,
  "repair_all_files_per_call": true,
  "pipeline_first_generation_during_baseline": true,
  "stream_evaluate_candidates": true,
  "pre_materialize_built_candidates": true,
  "random_seed": 1234,
  "score_pattern": "SCORE\\s*[:=]\\s*(-?\\d+(?:\\.\\d+)?)",
  "compile_error_markers": ["compilation_error"],
  "keep_failed_candidates": true,
  "keep_successful_candidates": true,
  "use_hardlink_copy": false,
  "command_timeout_sec": 0,
  "llm": {
    "endpoint": "http://127.0.0.1:8000/v1/chat/completions",
    "headers": {
      "Content-Type": "application/json",
      "Authorization": "Bearer YOUR_TOKEN"
    },
    "payload_template": {
      "model": "your-fast-model",
      "messages": [
        {"role": "system", "content": "${system}"},
        {"role": "user", "content": "${user}"}
      ],
      "temperature": "${temperature}",
      "max_tokens": "${max_output_tokens}"
    },
    "response_text_path": "choices.0.message.content",
    "timeout_sec": 180,
    "temperature_plan": 0.9,
    "temperature_mutate": 1.0,
    "temperature_repair": 0.4,
    "max_output_tokens": 128000,
    "mutation_repair_output_token_multiplier": 2,
    "json_retry_attempts": 2,
    "json_retry_output_token_multiplier": 2,
    "json_retry_include_invalid_excerpt_chars": 12000
  }
}

